### PR TITLE
add 2829b

### PR DESCRIPTION
**Pull request by jbesraa**

### CODE REVIEW

**Comment by jbesraa** [comment]
@dunxen would appreciate a review please

**Comment by dunxen** [comment]
LGTM I think we just need to set the previous review club entry to past in this PR too.

**Comment by jbesraa** [comment]
> LGTM I think we just need to set the previous review club entry to past in this PR too.

sorry iam not sure what you mean

**Comment by dunxen** [comment]
> sorry iam not sure what you mean

On the last post we need to set the status from `upcoming` to `past`:

https://github.com/lightningdevkit/ldk-review-club/blob/a5a541a49008b3617341ec96c9ed31a1a066edd5/_posts/2024-02-23-%232829.md?plain=1#L9

**Comment by jbesraa** [comment]
Ah, done!

**Pull request merged**
